In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [2]:
train_data = pd.read_csv(r"C:\Users\sidhu\OneDrive\Desktop\Kaggle\Titanic - Machine Learning from Disaster\data\train.csv")
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
test_data = pd.read_csv(r"C:\Users\sidhu\OneDrive\Desktop\Kaggle\Titanic - Machine Learning from Disaster\data\train.csv")
test_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
surviving_women = train_data.loc[train_data.Sex == "female"]["Survived"]
percent_of_women_alive = sum(surviving_women)/len(surviving_women) * 100

print("% of women who survived : ",percent_of_women_alive)

% of women who survived :  74.20382165605095

In [5]:
surviving_men = train_data.loc[train_data.Sex == "male"]["Survived"]
percent_of_men_alive = sum(surviving_men)/len(surviving_men) * 100

print("% of men who survived : ", percent_of_men_alive)

% of men who survived :  18.890814558058924

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

y = train_data["Survived"]

features = ["Pclass", "Sex", "Parch", "SibSp"]

X = pd.get_dummies(train_data[features])
X_test = pd.get_dummies(test_data[features])

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

model = RandomForestClassifier(
    n_estimators = 100,
    max_depth = 5,
    min_samples_split = 15,
    min_samples_leaf = 20,
    max_features = "sqrt",
    random_state=1
)

model.fit(X_train, y_train)

val_predictions = model.predict(X_val)

val_accuracy = accuracy_score(y_val, val_predictions)

print("Validation accuracy percentage :", val_accuracy * 100, "%")

Validation accuracy percentage : 80.44692737430168 %

In this version, i created a validation split from my training data to validate the accuracy of my results.

 I also manually played around with different hyperparamter values but found manual selection of ideal set of hyper parameter values to be inefficient and time consuming. So I decided to automate this process in the next version.